### ISSUE TITLE
Ensure Stream Enrich resolver uses cacheTtl of one

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-mini#137]
cc/ @alexanderdean

**Comment by alexanderdean** [comment]
Need to think about this one as in theory a user can control the whole Iglu resolver file, but we want to encourage using one with a zero cacheTtl...

**Comment by alexanderdean** [comment]
0.4.0 was already in progress, assigning to 0.5.0

**Comment by alexanderdean** [comment]
Bringing forwards.

**Comment by oguzhanunlu** [comment]
@alexanderdean @chuwy There is an issue with using `cacheTtl` of 0. 

resolver-config [`1-0-2`](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-2#L19-L22) indicates `cacheTtl` can be at least 1. If we definitely want to use 0, we need to add a new schema to iglu-central but in this case iglu scala client would not recognize since its resolver is [based on](https://github.com/snowplow/iglu-scala-client/blob/master/src/main/scala/com.snowplowanalytics.iglu/client/Resolver.scala#L54) `1-0-2`.

Would using `cacheTtl` of 1 be any problem?

**Comment by chuwy** [comment]
I think regardless of this ticket, we should add `1-0-3` schema to Iglu Central and create a ticket in iglu client to loosen config's criterion.

**Comment by alexanderdean** [comment]
Agree, thanks.
